version: '3.8'

services:
  backend:
    build: ./app
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    
  frontend:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend